"""
Main Pipeline Script

Orchestrates the full data pipeline: harvest -> parse -> manifest generation.
"""

import argparse
import logging
import json
from pathlib import Path
from typing import List, Dict, Optional
from collin_harvest import CollinElectionDataEngine
from unified_parser import parse_election_file, write_parsed_races, categorize_election_python
from manifest_generator import generate_manifest, format_display_name

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def load_master_index(index_path: str) -> List[Dict]:
    """
    Load the master index CSV generated by harvest.
    
    Args:
        index_path: Path to master index CSV
        
    Returns:
        List of file metadata dicts
    """
    import csv
    
    files = []
    with open(index_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            files.append({
                'election': row.get('election', ''),
                'year': int(row['year']) if row.get('year') and row['year'].isdigit() else None,
                'file_name': row.get('file_name', ''),
                'source_url': row.get('source_url', ''),
                'local_path': row.get('local_path', ''),
                'election_type': row.get('election_type', 'unknown')
            })
    
    return files


def run_pipeline(harvest_limit: Optional[int] = None, 
                use_existing_harvest: bool = False,
                harvest_dir: str = 'collin_elections_master',
                output_dir: str = 'data'):
    """
    Run the full pipeline: harvest -> parse -> manifest.
    
    Args:
        harvest_limit: Limit on number of election pages to harvest
        use_existing_harvest: If True, skip harvest and use existing files
        harvest_dir: Directory containing harvested files
        output_dir: Output directory for parsed CSVs
    """
    logger.info("=" * 60)
    logger.info("Starting Election Data Pipeline")
    logger.info("=" * 60)
    
    # Step 1: Harvest (or load existing)
    if use_existing_harvest:
        logger.info("Using existing harvest data")
        index_path = Path(harvest_dir) / 'collin_election_data_index.csv'
        if not index_path.exists():
            logger.error(f"Master index not found: {index_path}")
            logger.error("Run harvest first or set use_existing_harvest=False")
            return
        harvested_files = load_master_index(str(index_path))
    else:
        logger.info("Step 1: Harvesting election data...")
        engine = CollinElectionDataEngine(output_dir=harvest_dir)
        harvest_results = engine.run(limit=harvest_limit)
        
        if not harvest_results:
            logger.warning("No files harvested")
            return
        
        # Load master index
        index_path = Path(harvest_dir) / 'collin_election_data_index.csv'
        if index_path.exists():
            harvested_files = load_master_index(str(index_path))
        else:
            logger.error("Master index not generated")
            return
    
    logger.info(f"Harvested {len(harvested_files)} files")
    
    # Step 2: Parse files
    logger.info("\nStep 2: Parsing election files...")
    parsed_entries = []
    parse_errors = []
    
    for i, file_info in enumerate(harvested_files, 1):
        local_path = file_info['local_path']
        year = file_info.get('year')
        election_name = file_info.get('election', '')
        
        if not Path(local_path).exists():
            logger.warning(f"File not found: {local_path}")
            continue
        
        logger.info(f"Parsing {i}/{len(harvested_files)}: {Path(local_path).name}")
        
        try:
            # Parse the file
            parsed_races = parse_election_file(local_path, year=year, election_name=election_name)
            
            if not parsed_races:
                logger.warning(f"No races found in {local_path}")
                continue
            
            # Write parsed races to output directory
            output_files = write_parsed_races(parsed_races, output_dir=output_dir)
            
            # Add to manifest entries
            for race_data, output_file in zip(parsed_races, output_files):
                filename = Path(output_file).name
                category = categorize_election_python(filename)
                display_name = format_display_name(filename, year)
                
                parsed_entries.append({
                    'filename': filename,
                    'year': year,
                    'category': category,
                    'displayName': display_name
                })
        
        except Exception as e:
            logger.error(f"Error parsing {local_path}: {e}")
            parse_errors.append({'file': local_path, 'error': str(e)})
            continue
    
    logger.info(f"Parsed {len(parsed_entries)} race files")
    if parse_errors:
        logger.warning(f"Encountered {len(parse_errors)} parse errors")
    
    # Step 3: Generate manifest
    logger.info("\nStep 3: Generating manifest...")
    manifest_path = generate_manifest(parsed_entries, output_path=f'{output_dir}/elections.json')
    
    logger.info("=" * 60)
    logger.info("Pipeline Complete!")
    logger.info("=" * 60)
    logger.info(f"Parsed files: {len(parsed_entries)}")
    logger.info(f"Manifest: {manifest_path}")
    logger.info(f"Output directory: {output_dir}")
    
    if parse_errors:
        logger.info(f"\nParse errors ({len(parse_errors)}):")
        for error in parse_errors[:5]:  # Show first 5
            logger.info(f"  - {error['file']}: {error['error']}")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description='Election Data Pipeline')
    parser.add_argument('--harvest-limit', type=int, default=None,
                       help='Limit number of election pages to harvest')
    parser.add_argument('--use-existing', action='store_true',
                       help='Use existing harvest data (skip harvest step)')
    parser.add_argument('--harvest-dir', type=str, default='collin_elections_master',
                       help='Directory for harvested files')
    parser.add_argument('--output-dir', type=str, default='data',
                       help='Output directory for parsed CSVs')
    
    args = parser.parse_args()
    
    run_pipeline(
        harvest_limit=args.harvest_limit,
        use_existing_harvest=args.use_existing,
        harvest_dir=args.harvest_dir,
        output_dir=args.output_dir
    )


if __name__ == '__main__':
    main()
